### ISSUE TITLE
Morning session

### ISSUE THREAD

**Issue by jessicafarias** [balerum03/ror-social-scaffold#4]
Hello team you are doing it great, however, we notice you are stuck in the model, try to use double rows instead of 1, you can use this guide (friendship v1): https://smartfunnycool.com/friendships-in-activerecord/
After that you will understand more about models then you can read ruby guides to learn queries and scopes (friendship v2): https://guides.rubyonrails.org/active_record_querying.html

Good Luck!

**Comment by balerum03** [comment]
Thanks a lot, @jessicafarias
